version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/jobs_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - ./storage:/app/storage
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/jobs_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - ./storage:/app/storage
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
